spring:
# JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: product
  datasource:
    url: jdbc:postgresql://localhost:5432/prototype
    username: ${USERNAME:postgres}
    password: ${PASSWORD}
  jackson:
    serialization:
      write_dates_as_timestamps: false 
logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    context-path: /api/v1

basic-auth:
  data:
    user: admin
    password: password